<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <ApplicationIcon>icon.ico</ApplicationIcon>
  <OutputType>Exe</OutputType>
  <TargetFramework>net9.0</TargetFramework>   
  <LangVersion>default</LangVersion> 

  <Nullable>enable</Nullable>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

  <!-- 隐式命名空间引用 -->
  <ImplicitUsings>enable</ImplicitUsings>

  <!-- CS0168: 声明了变量，但未使用 -->
  <!-- CS0219: 给一个变量赋值却不使用该变量 -->
  <!-- CA1416: 某个方法只支持 Windows平台 -->
  <NoWarn>CS0168,CS0219,CA1416</NoWarn>

</PropertyGroup>

<!-- 发布模式：AOT，并裁剪体积 -->	
<PropertyGroup Condition="'$(Configuration)' != 'Debug'">
	<PublishAot>true</PublishAot>
	<PublishSingleFile>true</PublishSingleFile>
	<StripSymbols>true</StripSymbols>
	<PublishTrimmed>true</PublishTrimmed>
</PropertyGroup>

</Project>
